repos:
- repo: https://github.com/python/black
  rev: 21.9b0
  hooks:
    - id: black
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.2
  hooks:
    - id: flake8
      additional_dependencies: ['flake8-bugbear==21.4.3']
- repo: https://github.com/timothycrosley/isort
  rev: 5.9.1
  hooks:
    - id: isort
- repo: https://github.com/asottile/pyupgrade
  rev: v2.19.4
  hooks:
    - id: pyupgrade
      args: ["--py36-plus"]
- repo: https://github.com/gruntwork-io/pre-commit
  rev: v0.1.15
  hooks:
    - id: helmlint
