# These are the secrets that are needed if you want to override values
# in a secure way
apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: funcx_secrets
data:
  globusClient: <<client ID>>
  globusKey: <<secret key>>
  externalPostgresURI: <<postgresql://_____________>>