apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: maintain-deployments
  namespace: default
subjects:
- kind: User
  name: githubactions # "name" is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: Role
  name: eks-github-action-role
  apiGroup: rbac.authorization.k8s.io