# Default values for funcx.
# This is a YAML-formatted file.
ingress:
  enabled: false
  host: uc.ssl-hep.org

webService:
  image: funcx/web-service
  tag: dev
  pullPolicy: IfNotPresent

  dbSetupImage: funcx/web-service-db
  dbSetupTag: dev
  dbSetupPullPolicy: IfNotPresent

  advertisedRedisPort: 6379
  advertisedRedisHost: localhost

  replicas: 1
  globusClient: <<your app client>>
  globusKey: <<your app key>>

endpoint:
  enabled: true

funcx_endpoint:
  tag: dev
  funcXServiceAddress: http://funcx-funcx-web-service:8000

forwarder:
  enabled: true
  image: funcx/forwarder
  tag: configurable_ic_ports
  pullPolicy: IfNotPresent
  minInterchangePort: 54000
  maxInterchangePort: 54003

postgres:
  enabled: true

postgresql:
  postgresqlUsername: funcx
  postgresqlPassword: leftfoot1
  postgresqlDatabase: public

  persistence:
    enabled: true

redis:
  usePassword: false
  master:
    persistence:
      enabled: false
  slave:
    persistence:
      enabled: false


