# Default values for funcx.
# This is a YAML-formatted file.
ingress:
  enabled: false
  host: uc.ssl-hep.org

webService:
  image: funcx/web-service
  tag: dev
  pullPolicy: IfNotPresent

  dbSetupImage: funcx/web-service-db
  dbSetupTag: dev
  dbSetupPullPolicy: IfNotPresent

  advertisedRedisPort: 6379
  advertisedRedisHost: localhost

  replicas: 1
  globusClient: <<your app client>>
  globusKey: <<your app key>>

forwarderIP: host.docker.internal

endpoint:
  enabled: true
  image: funcx/kube-endpoint
  tag: dev
  pullPolicy: IfNotPresent
  replicas: 1

containerService:
  enabled: true
  image: funcx/container-service
  tag: dev
  pullPolicy: IfNotPresent

postgres:
  enabled: true

postgresql:
  postgresqlUsername: funcx
  postgresqlPassword: leftfoot1
  postgresqlDatabase: public

  persistence:
    enabled: true

redis:
  usePassword: false
  master:
    persistence:
      enabled: false
  slave:
    persistence:
      enabled: false


