# Default values for funcx.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
webService:
  image: funcx/web-service
  tag: 201_cleanup_repo
  pullPolicy: IfNotPresent

  dbSetupImage: funcx/web-service-db
  dbSetupTag: 213_helm_chart
  dbSetupPullPolicy: IfNotPresent

  replicas: 1
  host: localhost
  globusClient: <<your app client>>
  globusKey: <<your app key>>

postgres:
  enabled: true

postgresql:
  postgresqlUsername: funcx
  postgresqlPassword: leftfoot1
  postgresqlDatabase: public

  persistence:
    enabled: false

redis:
  usePassword: false
  master:
    persistence:
      enabled: false
  slave:
    persistence:
      enabled: false


