# Default values for funcx.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
webService:
  image: funcx/web-service
  tag: 201_cleanup_repo
  pullPolicy: IfNotPresent
  replicas: 1
  host: localhost
  globusClient: <<your app client>>
  globusKey: <<your app key>>

postgres:
  enabled: true

postgresql:
  postgresqlUsername: funcx
  postgresqlPassword: leftfoot1
  postgresqlDatabase: public
  initdbScriptsConfigMap: "{{ .Release.Name }}-init-scripts"

  persistence:
    enabled: false


