# Default values for funcx.
# This is a YAML-formatted file.
ingress:
  enabled: false
  host: uc.ssl-hep.org

webService:
  image: funcx/web-service
  tag: dev
  pullPolicy: IfNotPresent

  loglevel: DEBUG

  advertisedRedisPort: 6379
  advertisedRedisHost: localhost

  replicas: 1
  globusClient: <<your app client>>
  globusKey: <<your app key>>

endpoint:
  enabled: true

funcx_endpoint:
  tag: dev
  funcXServiceAddress: http://funcx-funcx-web-service:8000

forwarder:
  enabled: true
  image: funcx/forwarder
  tag: forwarder_redesign
  pullPolicy: IfNotPresent
  tasksPort: 55001
  resultsPort: 55002
  commandsPort: 55003

# External services - these should be included for development environment
# but on EKS we usually use the Amazon supported services
services:
  postgres:
    enabled: true
    externalURI: sqlite:////sqlite/app.db
  redis:
    enabled: true
    externalHost:
    externalPort: 6379

postgresql:
  postgresqlUsername: funcx
  postgresqlPassword: leftfoot1
  postgresqlDatabase: public

  persistence:
    enabled: false

redis:
  usePassword: false
  master:
    persistence:
      enabled: false
  slave:
    persistence:
      enabled: false


