{{- if .Values.forwarder.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-forwarder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-forwarder
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-forwarder
    spec:
      hostNetwork: true
      containers:
      - name: {{ .Release.Name }}-forwarder
        image: {{ .Values.forwarder.image }}:{{ .Values.forwarder.tag }}
        env:
        - name: REDIS_HOST
    {{- if .Values.services.redis.enabled }}
          value: ""
    {{- else }}
          value: "{{  .Values.services.redis.externalHost }}"
    {{- end }}
        - name: REDIS_PORT
    {{- if .Values.services.redis.enabled }}
          value: "6379"
    {{- else }}
          value: "{{  .Values.services.redis.externalPort }}"
    {{- end }}
        - name: RABBITMQ_URI
    {{- if .Values.services.rabbitmq.enabled }}
          value: ""
    {{- else }}
          value: "{{  .Values.services.rabbitmq.externalURI }}"
    {{- end }}
    {{- if not .Values.forwarder.useAWSMetadataServer }}
        - name: ADVERTISED_FORWARDER_ADDRESS
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
    {{- end }}
        - name: ENDPOINT_BASE_PORT
          value: "{{ .Values.forwarder.endpointBasePort }}"
        tty: true
        stdin: true
        imagePullPolicy: {{ .Values.forwarder.pullPolicy }}
        {{- if .Values.forwarder.resources }}
        resources:
{{ toYaml .Values.forwarder.resources | indent 10 }}
        {{- end }}
        ports:
          - containerPort: 8080  # Forwarder REST port
          - containerPort: {{ .Values.forwarder.endpointBasePort }}
            hostPort: {{ .Values.forwarder.endpointBasePort }}
          - containerPort: {{ add .Values.forwarder.endpointBasePort 1 }}
            hostPort: {{ add .Values.forwarder.endpointBasePort 1 }}
          - containerPort: {{ add .Values.forwarder.endpointBasePort 2 }}
            hostPort: {{ add .Values.forwarder.endpointBasePort 2 }}
        {{- if .Values.forwarder.server_cert }}
        volumeMounts:
        - name: funcx-forwarder-secret
          mountPath: /home/funcx/.curve
          readOnly: true
        {{- end }}
      {{- if .Values.forwarder.server_cert }}
      volumes:
      - name: funcx-forwarder-secret
        secret:
          secretName: funcx-forwarder-secrets
      {{- end }}
{{- end }}
