apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-web-service-config
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ .Release.Name }}
data:
  app.conf: |
    REDIS_PORT = 6379
    REDIS_HOST = "{{ .Release.Name }}-redis-master"

    ADVERTISED_REDIS_PORT = "{{ .Values.webService.advertisedRedisPort }}"
    ADVERTISED_REDIS_HOST = "{{ .Values.webService.advertisedRedisHost }}"
    HOSTNAME = "Not Used"
    GLOBUS_CLIENT = "{{ .Values.webService.globusClient }}"
    GLOBUS_KEY = "{{ .Values.webService.globusKey }}"

    {{ if .Values.postgres.enabled }}
    SQLALCHEMY_DATABASE_URI = 'postgresql://{{  .Values.postgresql.postgresqlUsername }}:{{ .Values.postgresql.postgresqlPassword }}@{{ .Release.Name }}-postgresql:5432/{{ .Values.postgresql.postgresqlDatabase }}'
    {{ else }}
    SQLALCHEMY_DATABASE_URI = 'sqlite:////sqlite/app.db'
    {{ end }}

    DB_NAME = "{{ .Values.postgresql.postgresqlDatabase }}"
    DB_USER = "{{ .Values.postgresql.postgresqlUsername }}"
    DB_PASSWORD = "{{ .Values.postgresql.postgresqlPassword }}"
    DB_HOST = "{{ .Release.Name }}-postgresql"

    FORWARDER_IP = "{{ .Release.Name }}-forwarder"
