#!/bin/bash

# require env vars
[ -n "$WEB_SERVICE_LOCAL_PORT" ] || exit 2
[ -n "$WEBSOCKET_SERVICE_LOCAL_PORT" ] || exit 2

cd "$(dirname "$0")"
set -euo pipefail

echo ">>> new port forwarding starts <<<" >> ./web-port-forward.log
kubectl port-forward service/funcx-funcx-web-service \
    "${WEB_SERVICE_LOCAL_PORT}:8000" \
    >> ./web-port-forward.log 2>&1 &
disown

echo ">>> new port forwarding starts <<<" >> ./websocket-port-forward.log
kubectl port-forward service/funcx-funcx-websocket-service \
    "${WEBSOCKET_SERVICE_LOCAL_PORT}:6000" \
    >> ./websocket-port-forward.log 2>&1 &
disown
