apiVersion: v1
kind: Pod
metadata:
  name: plsql
  labels:
    app: plsql
spec:
  containers:
  - image: dencold/pgcli
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
  restartPolicy: Always
